[package]
name = "chess-analyzers"
version = "0.1.0"
edition = "2021"

[dependencies]
shakmaty = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chess-core = { path = "../chess-core" }
