[package]
name = "chess-core"
version = "0.1.0"
edition = "2021"

[dependencies]
shakmaty = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
